package platform.qa.enums;

public enum Context {
    API_RESULT_LIST,
    API_RESULT_MAP,
    BPMN_FILE_NAMES,
    BPMN_FORM_KEY_LIST,
    BPMN_PROCESS_NAME_LIST,
    API_FORM_KEY_LIST,
    API_PROCESS_NAME_LIST,
    OFFICER_USER_LOGIN
}
